remote_theme: daattali/beautiful-jekyll@master
plugins:
  - jekyll-remote-theme

title: Historical and Architectural Landmark Recognizer
description: An image recognizer that recognizes 13 different historical and architectural landmarks

include:
  - _includes/footer.html


sass:
  style: compressed
